In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array

In [4]:
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [5]:
b = np.array([[1,2],[3,4]])   # Create a rank 2 array
print(b)
print(b.shape)

[[1 2]
 [3 4]]
(2, 2)


In [6]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [7]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [8]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [9]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [10]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.23227856 0.49810442]
 [0.18241632 0.41907959]]
